--
-- TABLE: CRUD_PERSON
--

CREATE TABLE persons_crud_db.CRUD_PERSON(
    ID_PERSON               		INT(9)    NOT NULL,
    NAME_PERSON						VARCHAR(255)	NOT NULL,
    ACTOR_NAME_PERSON				VARCHAR(255)	NOT NULL,
    HEIGHT_PERSON					INT(9)    NOT NULL,
    MASS_PERSON						INT(9)    NOT NULL,
    BIRTHDAY_PERSON					VARCHAR(255)	NOT NULL,
	GENDER_PERSON					VARCHAR(255)	NOT NULL,
    HOMEWORLD_PERSON				VARCHAR(255)	NOT NULL,
	SPECIES_PERSON					VARCHAR(255)	NOT NULL,
	CREATED_PERSON					VARCHAR(255)	NOT NULL,
	EDITED_PERSON					VARCHAR(255)	NOT NULL,
    CONSTRAINT PK_PERSON PRIMARY KEY (ID_PERSON)
)
;

--
-- SEQUENCE: SEQ_CRUD_PERSON
--

CREATE SEQUENCE persons_crud_db.SEQ_CRUD_PERSON
    START WITH 1
    INCREMENT BY 1
--  NOMINVALUE
--  NOMAXVALUE
    NOCACHE
--  NOORDER
;